name: jawara_pintar_mobile_version
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.1.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.2
  pdf: ^3.10.7
  printing: ^5.12.0
  share_plus: ^7.2.2
  supabase_flutter: ^2.10.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/background_login.jpg
    - .env
