name: jawara_pintar_mobile_version
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.10.3
  mocktail: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.7
  build_runner: ^2.10.4
  mockito: ^5.6.1
  bloc: ^9.1.0
  bloc_provider: ^1.0.0
  get_it: ^9.1.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/background_login.jpg
    - .env
